# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-29 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '展示'), (2, '下线')], default=1, verbose_name='状态'),
        ),
    ]
