# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-29 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180829_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(default='', help_text='目前支持markdown', verbose_name='渲染后的数据'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_markdown',
            field=models.BooleanField(default=True, verbose_name='是否使用markdown'),
        ),
    ]
