# Generated by Django 2.0.6 on 2018-09-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='用户的简介'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blog',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户博客地址'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='profile',
            name='html',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户github地址'),
        ),
    ]
