# Generated by Django 2.0.6 on 2018-09-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180919_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户所在地址'),
        ),
    ]
