# Generated by Django 2.0.6 on 2018-09-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='html',
            field=models.TextField(default='', verbose_name='渲染后的数据'),
        ),
        migrations.AddField(
            model_name='postcommentreply',
            name='html',
            field=models.TextField(default='', verbose_name='渲染后的数据'),
        ),
    ]
